name: Deploy VitePress site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build with VitePress
        run: bun run docs:build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: docs/.vitepress/dist
